### PR TITLE
Bugfix: A name within a valid json object must be followed by a ':' and ...

### PR DESCRIPTION
**Pull request by freemine**
Fact: previously {"x"} would be parsed with no error message, but {"x"} is really not a valid json

By adding an intermediate state (CLOSE_FIRST_KEY) in clarinet.js and some parsing logic modification,
it's fixed up as wish.

A bunch of new tests are inserted into test/clarinet.js, and all passing.

### CODE REVIEW

**Comment by dscape** [comment]
Thanks for this. However for this to be considered you need to make it an option (e.g. `strict: true`) and have the option default to `false`, as the current behavior is depend ended upon many people (and clarinet was designed not to be strict, hence this is deliberate)

If you can make this an option, add documentation for this new strict mode that emits error when json is invalid i'll merge it in

it's very important to understand if performance characteristics of the non-strict version remain the same, so there might be some work there to.

Let me know what you think. If you are not up for this work, I suggest you fork clarinet and call it something else (e.g. `clarinet-strict`)

Thanks for the awesome work and contributing to the project!

**Comment by jimhigson** [comment]
If this is breaking behaviour, and people depend on the old behaviour not
changing, perhaps this belongs in a new major (semantic) version?

**Comment by dscape** [comment]
@jimhigson yes, Also no reason to change the default unless a significative amount of people indicate that they would expect a strict behavior. `clarinet` is not, by default, that. i've used it `wrongly` in the past and it's great for less than tidy documents, and quick and dirty reduce jobs

**Comment by jimhigson** [comment]
Yes fair. And how common is invalid JSON anyway? I don't think I've
personally ever hit an endpoint and gotten a syntactically invalid response.

**Comment by dscape** [comment]
Agree. TCP corrects transmissions errors, so we are left with errors on the other side of the wire or in node core which seem unlikely. If that is the case, having a `strict` mode helps but only if:

1. it does not affect performance for those who do not use it
2. it's not the default, since for the majority of the use cases it's probably only `good to have`

**Comment by freemine** [comment]
@dscape, Thanks for the comment, and I totally argee. I'll follow as you suggested, working on it now.

**Pull request closed without merging**
